
title: shitposting mental
# email: diegoalvarado26@hotmail.com

description: Pensamientos
url: "https://diegoalvarado26.github.io"
baseurl: "/blog"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# author:
#   name: Diego Alvarado
#   email: dmalvaradog26@gmail.com

github_username: diegoalvarado26

author: Diego Alvarado
email : dmalvaradog26@gmail.com
markdown: kramdown

twitter:
    username: diegoalvarado26
    card: summary

theme: minima

google-analytics: G-CRYY183FNQ
disqus: 
  shortname: diegoalvarado
  url: "https://diegoalvarado26.github.io/"

minima:
  date_format: "%b %-d, %Y"
  social_links:
        twitter: diegoalvarado26
        github: diegoalvarado26
        instagram: diegoalvarado.26

plugins:
 - jekyll-feed
 - jekyll-seo-tag
